version: "3"
services:
  grpc:
    build:
      context: .
      dockerfile: Dockerfile.grpcserver
    ports:
    - "9090:9090"
  http:
    build:
      context: .
      dockerfile: Dockerfile.httpserver
    ports:
      - "8080:8080"
  vault:
    image: vault
    cap_add:
    - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 12345678
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
    - 8200:8200