version: "3"
services:
  grpc:
    build:
      context: .
      dockerfile: Dockerfile.grpcserver
    ports:
    - "9090:9090"
  http:
    build:
      context: .
      dockerfile: Dockerfile.httpserver
    ports:
      - "8080:8080"
