version: "3.4"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  grpc:
    build:
      context: .
      dockerfile: Dockerfile
      target: grpcserver
    environment:
      GREETER: db
      DB_HOST: db # docker compose so the container image from above will resolve via dns
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: example
      DB_DBNAME: postgres
    ports:
    - "9090:9090"
  http:
    build:
      context: .
      dockerfile: Dockerfile
      target: httpserver
    ports:
      - "8080:8080"
  vault:
    image: vault
    cap_add:
    - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 12345678
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
    - "8200:8200"
  jwt:
    build:
      context: .
      dockerfile: Dockerfile
      target: jwtserver
    ports:
    - "8081:8081"