FROM golang:1.17-alpine AS builder

WORKDIR /app
# disable CGO, forces go to build staticly without clibs
#ENV CGO_ENABLED 0
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN #go test ./... # simple ci/cd check
RUN go build -o server cmd/server/main.go

FROM alpine:3.14

COPY --from=builder /app/server .

CMD ./server