version: "3.9"
services:
  grpc:
    image: grpcserver
    depends_on:
      - jwt
    environment:
      GREETER: db
      PORT: 9090
      DB_HOST: go_example_support_db # docker swarm so the container will resolve via dns
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: example
      DB_DBNAME: postgres
      VAULT_ADDR: "http://go_example_support_vault:8200"
      VAULT_TOKEN: "${VAULT_TOKEN}"
    ports:
    - "9090:9090"
    networks:
    - go_example
    volumes:
      - ./certs:/certs
    healthcheck:
      test: [ "CMD", "nc", "-zvw10", "localhost", "9090" ]
      interval: 1s
      timeout: 5s
      retries: 5
  http:
    image: httpserver
    ports:
      - "8080:8080"
    networks:
      - go_example
    healthcheck:
      test: [ "CMD", "nc", "-zvw10", "localhost", "8080" ]
      interval: 1s
      timeout: 5s
      retries: 5
  jwt:
    image: jwtserver
    ports:
    - "8081:8081"
    networks:
      - go_example
    healthcheck:
      test: [ "CMD", "nc", "-zvw10", "localhost", "8081" ]
      interval: 1s
      timeout: 5s
      retries: 5
networks:
  go_example:
    external: true
    name: go_example