version: "3.9"
services:
  vault:
    image: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 12345678
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    networks:
      - go_example
    healthcheck:
      test: [ "CMD", "nc", "-zvw10", "localhost", "8200" ]
      interval: 1s
      timeout: 5s
      retries: 5
  db:
    image: postgres
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - go_example
networks:
  go_example:
    external: true
    name: go_example