version: "3.9"
services:
  vault:
    image: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 12345678
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports:
      - "8200:8200"
    networks:
      - go_example
    healthcheck:
      test: [ "CMD", "nc", "-zvw10", "localhost", "8200" ]
      interval: 1s
      timeout: 5s
      retries: 5
  db:
    image: postgres
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 5
    networks:
      - go_example
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    hostname: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
    - go_example
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    hostname: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - go_example
  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    hostname: logstash
    ports:
      - "9600:9600"
      - "5044:5044"
    volumes:
      - ./.config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - go_example
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.2
    command: [ "filebeat", "-e", "-strict.perms=false" ]
    user: root
    depends_on:
      - logstash
    environment:
      - "strict.perms=false"
    volumes:
      - "./.config/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - go_example
networks:
  go_example:
    external: true
    name: go_example